/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.ui;

import com.group2.dao.GoiTapDAO;
import com.group2.entity.GioHangGT;
import com.group2.entity.GoiTap;
import com.group2.swing.Alert;
import com.group2.swing.EpisodePackModel;
import com.group2.swing.ScrollBarCustom;
import com.group2.utils.MsgBox;
import java.util.List;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author HieuHoang
 */
public class GioiTapUI extends javax.swing.JPanel {

    GoiTapDAO goiTapDAO = new GoiTapDAO();
    List<GoiTap> list = goiTapDAO.selectAll();

    /**
     * Creates new form GioiTapUI
     */
    public GioiTapUI() {
        initComponents();
        desginUI();
        main.setLayout(new MigLayout("wrap 4, insets 15"));
//        addItemGoiTap(new EpisodePackModel());
//        addItemGoiTap(new EpisodePackModel());
//        addItemGoiTap(new EpisodePackModel());
//        addItemGoiTap(new EpisodePackModel());
//        addItemGoiTap(new EpisodePackModel());
        LoadForSelected();

    }

    public void LoadForSelected() {
        main.removeAll();
        String cbo = (String) cboLoaiGT.getSelectedItem();
        for (GoiTap gt : list) {
            if (gt.getMaLoai().trim().equalsIgnoreCase(cbo.trim())) {

                addItemGoiTap(new EpisodePackModel(gt, cbo, gioHangGTPanel1));

            }
        }
        main.repaint();
    }

    public void addItemGoiTap(EpisodePackModel model) {
        main.add(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientBackGround1 = new com.group2.swing.GradientBackGround();
        jScrollPane1 = new javax.swing.JScrollPane();
        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboLoaiGT = new com.group2.swing.ComboBoxSuggestion();
        gioHangGTPanel1 = new com.group2.swing.GioHangGTPanel();

        setOpaque(false);

        gradientBackGround1.setBorderRadius(10);
        gradientBackGround1.setShadowSize(5);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        main.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(main);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 150, 150));
        jLabel1.setText("Thể loại");

        cboLoaiGT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gym", "Yoga", "Boxing" }));
        cboLoaiGT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboLoaiGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiGTActionPerformed(evt);
            }
        });

        gioHangGTPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gioHangGTPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout gradientBackGround1Layout = new javax.swing.GroupLayout(gradientBackGround1);
        gradientBackGround1.setLayout(gradientBackGround1Layout);
        gradientBackGround1Layout.setHorizontalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoaiGT, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gioHangGTPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        gradientBackGround1Layout.setVerticalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(cboLoaiGT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gioHangGTPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiGTActionPerformed
        // TODO add your handling code here:
        LoadForSelected();
    }//GEN-LAST:event_cboLoaiGTActionPerformed

    private void gioHangGTPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gioHangGTPanel1MousePressed
        // TODO add your handling code here:
        if (GioHangGT.listGT.size() == 0) {
            MsgBox.alert(null, "Giỏ hàng trống", "Vui lòng chọn gói tập!", Alert.AlertType.ERROR);

        } else {
            new HoaDonGoiTapJDailog(gioHangGTPanel1).setVisible(true);

        }
    }//GEN-LAST:event_gioHangGTPanel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.ComboBoxSuggestion cboLoaiGT;
    private com.group2.swing.GioHangGTPanel gioHangGTPanel1;
    private com.group2.swing.GradientBackGround gradientBackGround1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables

    private void desginUI() {
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        jScrollPane1.setHorizontalScrollBar(new ScrollBarCustom());
    }
}
