/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.ui;

import com.group2.dao.CheckInDAO;
import com.group2.dao.ThongKeDAO;
import com.group2.entity.ChekIn;
import com.group2.entity.ThongKe;
import com.group2.swing.Card;
import com.group2.swing.HoiVienDateTime;
import com.group2.swing.HoiVienDateTimeUI;
import com.group2.swing.HoiVienItemUI;
import com.group2.swing.ProductHot;
import com.group2.swing.ProductHotUI;
import com.group2.swing.ScrollBarCustom;
import com.group2.utils.GDate;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.SwingUtilities;

/**
 *
 * @author HieuHoang
 */
public class HomeUI extends javax.swing.JPanel {

    List<ThongKe> listThongKe, listThongKeHVHetHan;
    DefaultListModel<String> dlmList1 = new DefaultListModel<>();
    DefaultListModel<HoiVienDateTime> dlmList3 = new DefaultListModel<>();
    DefaultListModel<ProductHot> dlmList2 = new DefaultListModel<>();
    ThongKeDAO tkdao = new ThongKeDAO();
    CheckInDAO checkInDAO = new CheckInDAO();
    List<ChekIn> listCheckIn = checkInDAO.selectAll();

    /**
     * Creates new form HomeUI
     */
    public HomeUI() {
        initComponents();
        dlmList1 = new DefaultListModel<>();
        dlmList3 = new DefaultListModel<>();
        dlmList2 = new DefaultListModel<>();
        tkdao = new ThongKeDAO();
        checkInDAO = new CheckInDAO();
        //  thiết kế lại thanh cuộn
        designScrollBar();
        jList1.setModel(dlmList1);
        jList3.setModel(dlmList3);
        jList2.setModel(dlmList2);
        card4.setTitile("Số hội viên check in");
        card4.setGradientColor(new Color(0, 4, 40), new Color(0, 78, 146));
        card2.setGradientColor(new Color(53, 92, 125), new Color(53, 92, 125));
        card3.setGradientColor(new Color(31, 64, 55), new Color(31, 64, 55));
        card2.setIcon(new ImageIcon(getClass().getResource("/com/group2/icons/icons8_ingredients_for_cooking_100px_1.png")));
        card3.setIcon(new ImageIcon(getClass().getResource("/com/group2/icons/icons8_male_user_100px.png")));

        card2.setTitile("Số SP bán trong tháng");
        card3.setTitile("Số hội viên sắp hết hạn");
        soSpBanTrongThang(tkdao.AVGSP());
        HVHetHan(tkdao.HVSapHetHan());
        fillToList();
    }

    public DefaultListModel<String> getDlmList1() {
        return dlmList1;
    }

    public void setDlmList1(DefaultListModel<String> dlmList1) {
        this.dlmList1 = dlmList1;
    }


    private void fillToList() {
        dlmList1.removeAllElements();
        for (ChekIn chekIn : checkInDAO.SoHVCheckIn()) {
            dlmList1.addElement(chekIn.toString());
        }
        card4.setTextJlabel(checkInDAO.SoHVCheckIn().size() + "");

    }

    public Card getCard4() {
        return card4;
    }

    public void setCard4(Card card4) {
        this.card4 = card4;
    }

    public void soSpBanTrongThang(List<ThongKe> list) {
        dlmList2.removeAllElements();
        for (ThongKe tk : list) {
            dlmList2.addElement(new ProductHot(tk.getMaSP(), tk.getTenSP(), tk.getSoLuong()));
        }
        card2.setTextJlabel(String.valueOf(list.size()));

    }

    public void HVHetHan(List<ThongKe> list) {
        dlmList3.removeAllElements();
        if (list.size() > 0) {
            for (ThongKe tk : list) {
                dlmList3.addElement(new HoiVienDateTime(tk.getHoTen(), tk.getSoDT(), GDate.toDate(tk.getNgayHetHan(), "yyyy-MM-dd")));
            }
        }
        card3.setTextJlabel(String.valueOf(list.size()));
    }

    public void designScrollBar() {
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());

        jScrollPane1.setHorizontalScrollBar(new ScrollBarCustom());
        jScrollPane2.setVerticalScrollBar(new ScrollBarCustom());

        jScrollPane2.setHorizontalScrollBar(new ScrollBarCustom());
        jScrollPane3.setVerticalScrollBar(new ScrollBarCustom());

        jScrollPane3.setHorizontalScrollBar(new ScrollBarCustom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientBackGround1 = new com.group2.swing.GradientBackGround();
        gradientBackGround2 = new com.group2.swing.GradientBackGround();
        card2 = new com.group2.swing.Card();
        card3 = new com.group2.swing.Card();
        card4 = new com.group2.swing.Card();
        gradientBackGround3 = new com.group2.swing.GradientBackGround();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        gradientBackGround4 = new com.group2.swing.GradientBackGround();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        gradientBackGround5 = new com.group2.swing.GradientBackGround();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        gradientBackGround1.setBorderRadius(5);
        gradientBackGround1.setShadowOpacity(0.3F);
        gradientBackGround1.setShadowSize(5);

        gradientBackGround2.setBorderRadius(10);
        gradientBackGround2.setShadowColor(new java.awt.Color(102, 204, 255));
        gradientBackGround2.setShadowSize(3);

        card2.setBorderRadius(10);
        card2.setColorEnd(new java.awt.Color(0, 4, 40));
        card2.setColorStart(new java.awt.Color(0, 78, 146));

        card3.setBorderRadius(10);
        card3.setColorEnd(new java.awt.Color(0, 4, 40));
        card3.setColorStart(new java.awt.Color(0, 78, 146));

        card4.setBorderRadius(10);
        card4.setColorEnd(new java.awt.Color(0, 4, 40));
        card4.setColorStart(new java.awt.Color(0, 78, 146));

        javax.swing.GroupLayout gradientBackGround2Layout = new javax.swing.GroupLayout(gradientBackGround2);
        gradientBackGround2.setLayout(gradientBackGround2Layout);
        gradientBackGround2Layout.setHorizontalGroup(
            gradientBackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBackGround2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(card4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        gradientBackGround2Layout.setVerticalGroup(
            gradientBackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gradientBackGround3.setBorderRadius(5);
        gradientBackGround3.setShadowColor(new java.awt.Color(153, 255, 255));
        gradientBackGround3.setShadowSize(4);

        jLabel2.setBackground(new java.awt.Color(0, 153, 255));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(2, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách hội viên đã check in trong ngày");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.setCellRenderer(new HoiVienItemUI());
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout gradientBackGround3Layout = new javax.swing.GroupLayout(gradientBackGround3);
        gradientBackGround3.setLayout(gradientBackGround3Layout);
        gradientBackGround3Layout.setHorizontalGroup(
            gradientBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(gradientBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBackGround3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        gradientBackGround3Layout.setVerticalGroup(
            gradientBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(gradientBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gradientBackGround3Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );

        gradientBackGround4.setBorderRadius(5);
        gradientBackGround4.setShadowColor(new java.awt.Color(153, 255, 255));
        gradientBackGround4.setShadowSize(4);

        jLabel3.setBackground(new java.awt.Color(0, 153, 102));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(2, 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Top 5 sản phẩm bán chạy nhất trong tháng");

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList2.setCellRenderer(new ProductHotUI());
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout gradientBackGround4Layout = new javax.swing.GroupLayout(gradientBackGround4);
        gradientBackGround4.setLayout(gradientBackGround4Layout);
        gradientBackGround4Layout.setHorizontalGroup(
            gradientBackGround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(gradientBackGround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBackGround4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        gradientBackGround4Layout.setVerticalGroup(
            gradientBackGround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(gradientBackGround4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gradientBackGround4Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );

        gradientBackGround5.setBorderRadius(5);
        gradientBackGround5.setShadowColor(new java.awt.Color(153, 255, 255));
        gradientBackGround5.setShadowSize(4);

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(2, 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Danh sách hội viên sắp hết hạn");

        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList3.setCellRenderer(new HoiVienDateTimeUI());
        jScrollPane3.setViewportView(jList3);

        javax.swing.GroupLayout gradientBackGround5Layout = new javax.swing.GroupLayout(gradientBackGround5);
        gradientBackGround5.setLayout(gradientBackGround5Layout);
        gradientBackGround5Layout.setHorizontalGroup(
            gradientBackGround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(gradientBackGround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBackGround5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        gradientBackGround5Layout.setVerticalGroup(
            gradientBackGround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(gradientBackGround5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gradientBackGround5Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout gradientBackGround1Layout = new javax.swing.GroupLayout(gradientBackGround1);
        gradientBackGround1.setLayout(gradientBackGround1Layout);
        gradientBackGround1Layout.setHorizontalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradientBackGround2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addComponent(gradientBackGround3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradientBackGround4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradientBackGround5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        gradientBackGround1Layout.setVerticalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradientBackGround2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradientBackGround3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradientBackGround4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradientBackGround5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.Card card2;
    private com.group2.swing.Card card3;
    private com.group2.swing.Card card4;
    private com.group2.swing.GradientBackGround gradientBackGround1;
    private com.group2.swing.GradientBackGround gradientBackGround2;
    private com.group2.swing.GradientBackGround gradientBackGround3;
    private com.group2.swing.GradientBackGround gradientBackGround4;
    private com.group2.swing.GradientBackGround gradientBackGround5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<ProductHot> jList2;
    private javax.swing.JList<HoiVienDateTime> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
