/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.ui;

import com.group2.dao.NhanVienDAO;
import com.group2.entity.NhanVien;
import com.group2.swing.Alert;
import com.group2.swing.AvataTbNhanVien;
import com.group2.swing.ScrollBarCustom;
import com.group2.utils.GDate;
import com.group2.utils.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HieuHoang
 */
public class NhanVienUI extends javax.swing.JPanel {

    boolean th = true;
    NhanVienDAO nvDAO = new NhanVienDAO();
    DefaultTableModel model;

    /**
     * Creates new form NhanVienUI
     */
    public NhanVienUI() {
        initComponents();
        tblNhanVien.getColumnModel().getColumn(0).setCellRenderer(new AvataTbNhanVien());
        designTable();
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuLamMoi = new javax.swing.JMenuItem();
        menuXoa = new javax.swing.JMenuItem();
        menuSua = new javax.swing.JMenuItem();
        gradientBackGround1 = new com.group2.swing.GradientBackGround();
        txtTim = new com.group2.swing.TextField();
        btnThemNhanVien = new com.group2.swing.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        menuLamMoi.setText("Làm mới bảng");
        menuLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLamMoiActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuLamMoi);

        menuXoa.setText("Xóa nhân viên");
        menuXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuXoaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuXoa);

        menuSua.setText("Sửa nhân viên");
        menuSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuSua);

        setOpaque(false);

        gradientBackGround1.setBorderRadius(10);
        gradientBackGround1.setShadowColor(new java.awt.Color(0, 4, 40));
        gradientBackGround1.setShadowSize(5);

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTim.setLabelText("Tìm kiếm nhân viên");
        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKeyReleased(evt);
            }
        });

        btnThemNhanVien.setBackground(new java.awt.Color(255, 51, 0));
        btnThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNhanVien.setText("+ Thêm nhân viên");
        btnThemNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });

        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Số ĐT", "Họ tên", "Chức vụ", "Ngày sinh", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setRowHeight(25);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        javax.swing.GroupLayout gradientBackGround1Layout = new javax.swing.GroupLayout(gradientBackGround1);
        gradientBackGround1.setLayout(gradientBackGround1Layout);
        gradientBackGround1Layout.setHorizontalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBackGround1Layout.createSequentialGroup()
                        .addComponent(txtTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addContainerGap())
        );
        gradientBackGround1Layout.setVerticalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            jPopupMenu1.show(tblNhanVien, evt.getX(), evt.getY());
        } else if (evt.getClickCount() == 2) {
            th = false;
            NhanVien nv = nvDAO.selectById((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0));
            new ChiTietNhanVienJDailog(th,nv,tblNhanVien).setVisible(true);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void menuLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLamMoiActionPerformed
        fillToTable();
    }//GEN-LAST:event_menuLamMoiActionPerformed

    private void txtTimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyReleased
        timNhanVien();
    }//GEN-LAST:event_txtTimKeyReleased

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        // TODO add your handling code here:
        th = true;
        //NhanVien nv = nvDAO.selectById((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0));
        new ChiTietNhanVienJDailog(th).setVisible(true);
        fillToTable();
    }//GEN-LAST:event_btnThemNhanVienActionPerformed

    private void menuXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuXoaActionPerformed
        xoaNhanvien();
        fillToTable();
    }//GEN-LAST:event_menuXoaActionPerformed

    private void menuSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuaActionPerformed
        th = false;
        NhanVien nv = nvDAO.selectById((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0));
        new ChiTietNhanVienJDailog(th, nv,tblNhanVien).setVisible(true);
        fillToTable();
    }//GEN-LAST:event_menuSuaActionPerformed

    private void designTable() {
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        jScrollPane1.setHorizontalScrollBar(new ScrollBarCustom());
        tblNhanVien.getTableHeader().setBackground(new Color(19, 28, 129));
        tblNhanVien.getTableHeader().setForeground(Color.WHITE);
        tblNhanVien.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 13));
        tblNhanVien.getTableHeader().setOpaque(false);
    }

    public void fillToTable() {
        model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        List<NhanVien> listNV = nvDAO.selectAll();
        for (NhanVien nv : listNV) {
            Object row[] = {nv.getMaNV(),nv.getSoDT(),nv.getHoTen(), nv.getChucVu(), GDate.toString(nv.getNgaySinh(), "dd/MM/yyyy"), nv.getDiaChi()};
            model.addRow(row);
        }
    }

    private void timNhanVien() {
        model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        List<NhanVien> listNV = nvDAO.timNhanVien("%" + txtTim.getText() + "%", "%" + txtTim.getText() + "%");
        for (NhanVien nv : listNV) {
            Object row[] = {nv.getMaNV(), nv.getSoDT(), nv.getHoTen(), nv.getChucVu(), GDate.toString(nv.getNgaySinh(), "dd/MM/yyyy"), nv.getDiaChi()};
            model.addRow(row);
        }
    }

    private void xoaNhanvien() {
        try {
            if (MsgBox.confirm(null, "Bạn có muốn xóa nhân viên này không ?")) {
                nvDAO.delete((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0));
                MsgBox.alert(null, "Thông báo", "Xóa nhân viên thành công!", Alert.AlertType.SUCCESS);
                fillToTable();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.Button btnThemNhanVien;
    private com.group2.swing.GradientBackGround gradientBackGround1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuLamMoi;
    private javax.swing.JMenuItem menuSua;
    private javax.swing.JMenuItem menuXoa;
    private javax.swing.JTable tblNhanVien;
    private com.group2.swing.TextField txtTim;
    // End of variables declaration//GEN-END:variables
}
