/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.ui;

import com.group2.dao.SanPhamDAO;
import com.group2.entity.SanPham;
import com.group2.swing.AvataSanPham;
import com.group2.swing.AvataTbHoiVien;
import com.group2.swing.ProductModel;
import com.group2.swing.ScrollBarCustom;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HieuHoang
 */
public class QLSanPhamUI extends javax.swing.JPanel {

    /**
     * Creates new form QLSanPhamUI
     */
    DefaultTableModel model;
    SanPhamDAO spDAO = new SanPhamDAO();
    boolean th = true;
    DecimalFormat df = new DecimalFormat("###,###.###");

    public QLSanPhamUI() {
        initComponents();
        designTable();
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuLamMoi = new javax.swing.JMenuItem();
        mnuSua = new javax.swing.JMenuItem();
        gradientBackGround1 = new com.group2.swing.GradientBackGround();
        txtTim = new com.group2.swing.TextField();
        btnThem = new com.group2.swing.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        cboLoaiSP = new com.group2.swing.ComboBoxSuggestion();

        mnuLamMoi.setText("Làm mới bảng");
        mnuLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLamMoiActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuLamMoi);

        mnuSua.setText("Sửa");
        mnuSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSuaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuSua);

        setOpaque(false);

        gradientBackGround1.setBorderRadius(10);
        gradientBackGround1.setShadowSize(5);

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTim.setLabelText("Tìm kiếm sản phẩm");
        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKeyReleased(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 0, 0));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("+ Thêm sản phẩm");
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tblSanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Đơn giá", "Số lượng", "Nhà sản xuất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setRowHeight(25);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        tblSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSanPhamKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        cboLoaiSP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Sữa tăng cân", "Sữa tăng cơ", "Phụ kiện thân trên", "Thời trang fitness", "Thực phẩm và tạp hóa thể thao", "Phụ kiện thân dưới", "Vitamin và khoáng chất", "Tăng sức mạnh", "BCAA và Amino Acids" }));
        cboLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientBackGround1Layout = new javax.swing.GroupLayout(gradientBackGround1);
        gradientBackGround1.setLayout(gradientBackGround1Layout);
        gradientBackGround1Layout.setHorizontalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addComponent(cboLoaiSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        gradientBackGround1Layout.setVerticalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        th = false;
        new ChiTietSanPhamJDailog(th).setVisible(true);
        fillToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyReleased
        // TODO add your handling code here:
        timSanPham();
    }//GEN-LAST:event_txtTimKeyReleased

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            jPopupMenu1.show(tblSanPham, evt.getX(), evt.getY());
        } else if (evt.getClickCount() == 2) {
            th = true;
            SanPham sp = spDAO.selectById((String) tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 0));
            new ChiTietSanPhamJDailog(th, sp).setVisible(true);
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void mnuSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSuaActionPerformed
        // TODO add your handling code here:
        th = true;
        SanPham sp = spDAO.selectById((String) tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 0));
        new ChiTietSanPhamJDailog(th, sp).setVisible(true);
        fillToTable();
    }//GEN-LAST:event_mnuSuaActionPerformed

    private void mnuLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLamMoiActionPerformed
        fillToTable();
    }//GEN-LAST:event_mnuLamMoiActionPerformed

    private void tblSanPhamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSanPhamKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPhamKeyPressed

    private void cboLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSPActionPerformed
        // TODO add your handling code here:
        fillToTable();
    }//GEN-LAST:event_cboLoaiSPActionPerformed
    private void designTable() {
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        jScrollPane1.setHorizontalScrollBar(new ScrollBarCustom());
        tblSanPham.getTableHeader().setBackground(new Color(107, 149, 183));
        tblSanPham.getTableHeader().setForeground(Color.WHITE);
        tblSanPham.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 13));
        tblSanPham.getTableHeader().setOpaque(false);
        tblSanPham.getColumnModel().getColumn(0).setCellRenderer(new AvataSanPham());

    }

    private void fillToTable() {
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        String LoaiSP = (String) cboLoaiSP.getSelectedItem();
        List<SanPham> listNV = spDAO.getLoaiSP();
        for (SanPham sp : listNV) {
            if (LoaiSP.equals("Tất cả")) {
                Object row[] = {sp.getMaSP(), sp.getTenSP(), df.format(sp.getDonGia()) + "₫", sp.getSoLuong(), sp.getNhaSanXuat()};
                model.addRow(row);
                continue;
            } else if (LoaiSP.equals(sp.getTenLoai())) {
                Object row[] = {sp.getMaSP(), sp.getTenSP(), df.format(sp.getDonGia()) + "₫", sp.getSoLuong(), sp.getNhaSanXuat()};
                model.addRow(row);
                continue;
            }
        }
    }

    private void timSanPham() {
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        List<SanPham> listSP = spDAO.timSanPham("%" + txtTim.getText() + "%", "%" + txtTim.getText() + "%");
        for (SanPham sp : listSP) {
            Object row[] = {sp.getMaSP(), sp.getTenSP(), df.format(sp.getDonGia()) + "₫", sp.getSoLuong(), sp.getNhaSanXuat()};
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.Button btnThem;
    private com.group2.swing.ComboBoxSuggestion cboLoaiSP;
    private com.group2.swing.GradientBackGround gradientBackGround1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuLamMoi;
    private javax.swing.JMenuItem mnuSua;
    private javax.swing.JTable tblSanPham;
    private com.group2.swing.TextField txtTim;
    // End of variables declaration//GEN-END:variables
}
