/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.swing;

import com.group2.entity.GioHangSP;
import java.awt.Color;

/**
 *
 * @author HieuHoang
 */
public class CartModel extends javax.swing.JPanel {

    /**
     * Creates new form CartModel
     */
    
    public CartModel() {
        initComponents();
        conBtn1.setBackground(new Color(255,0,0,90));
//        conBtn1.setText(""+GioHangSP.listSP.size());
    }

    public ConBtn getConBtn1() {
        return conBtn1;
    }

    public void setConBtn1(ConBtn conBtn1) {
        this.conBtn1 = conBtn1;
    }
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageView1 = new com.group2.swing.ImageView();
        conBtn1 = new com.group2.swing.ConBtn();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageView1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icons/icons8_shopping_cart_48px_1.png"))); // NOI18N

        conBtn1.setBackground(new java.awt.Color(255, 0, 51));
        conBtn1.setForeground(new java.awt.Color(255, 255, 255));
        conBtn1.setText("1");
        conBtn1.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        conBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conBtn1ActionPerformed(evt);
            }
        });
        imageView1.add(conBtn1);
        conBtn1.setBounds(10, 0, 30, 20);

        add(imageView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void conBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.ConBtn conBtn1;
    private com.group2.swing.ImageView imageView1;
    // End of variables declaration//GEN-END:variables
}
