/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.swing;

import com.group2.dao.GoiTapDAO;
import com.group2.entity.GioHangGT;
import com.group2.entity.GoiTap;
import com.group2.ui.GymSysJFrame;
import com.group2.ui.HoaDonGoiTapJDailog;

import com.group2.utils.MsgBox;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author HieuHoang
 */
public class EpisodePackModel extends javax.swing.JPanel {

    GoiTapDAO dao = new GoiTapDAO();

    List<GoiTap> list = dao.selectAll();
    DecimalFormat df = new DecimalFormat("###,###.###");
    private GoiTap gt;
    private GioHangGTPanel gioHangGTPanel;

    /**
     * Creates new form EpisodePack
     */
    public EpisodePackModel(GoiTap gt, String ten, GioHangGTPanel gioHangGTPanel) {
        this.gt = gt;
        this.gioHangGTPanel = gioHangGTPanel;
        initComponents();
        loadProduct(gt, ten);
    }
    public void loadProduct(GoiTap gt,String ten){
        btnMua.setName(gt.getMaGT());
        ngay.setText(String.valueOf(gt.getThoiLuong()));
        maGT.setText(gt.getMaGT());
        gia.setText(df.format(gt.getGia()) + "₫");
        tenLoai.setText("Gói tập " + ten);
        imageView1.setImage(new ImageIcon(getClass().getResource("/com/group2/icons/" + gt.getMaLoai().trim() + ".png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientBackGround1 = new com.group2.swing.GradientBackGround();
        imageView1 = new com.group2.swing.ImageView();
        tenLoai = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ngay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gia = new javax.swing.JLabel();
        maGT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMua = new com.group2.swing.Button();
        button1 = new com.group2.swing.Button();

        setOpaque(false);

        gradientBackGround1.setBorderRadius(10);

        imageView1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icons/icons8_combi_ticket_48px_1.png"))); // NOI18N

        tenLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tenLoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenLoai.setText("Gói Tập Gym");

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setOpaque(true);

        ngay.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ngay.setForeground(new java.awt.Color(0, 0, 153));
        ngay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ngay.setText("30");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Mã:");

        gia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gia.setForeground(new java.awt.Color(255, 0, 0));
        gia.setText("200.000₫");

        maGT.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        maGT.setForeground(new java.awt.Color(0, 102, 102));
        maGT.setText("Gym01");

        btnMua.setBackground(new java.awt.Color(0, 153, 204));
        btnMua.setForeground(new java.awt.Color(255, 255, 255));
        btnMua.setText("Mua ngay");
        btnMua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(204, 0, 0));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Thêm vào giỏ");
        button1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientBackGround1Layout = new javax.swing.GroupLayout(gradientBackGround1);
        gradientBackGround1.setLayout(gradientBackGround1Layout);
        gradientBackGround1Layout.setHorizontalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBackGround1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imageView1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(maGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addComponent(btnMua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gradientBackGround1Layout.setVerticalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imageView1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(maGT)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gia)
                .addGap(18, 18, 18)
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaActionPerformed
        // TODO add your handling code here:
        GioHangGT.clearGT();
        GioHangGT.themGTVaoGH(gt);
        gioHangGTPanel.setSLGoiTap();
        new HoaDonGoiTapJDailog(gioHangGTPanel).setVisible(true);
    }//GEN-LAST:event_btnMuaActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (!GioHangGT.themGTVaoGH(gt)) {
            MsgBox.alert(null, "Gói tập đã có trong giỏ hàng!", "Vui lòng chọn gói tập mới!", Alert.AlertType.ERROR);

        } else {
            MsgBox.alert(null, "Thông báo", "Thêm gói tập vào giỏ hàng thành công!", Alert.AlertType.SUCCESS);

        }
        gioHangGTPanel.setSLGoiTap();

    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.Button btnMua;
    private com.group2.swing.Button button1;
    private javax.swing.JLabel gia;
    private com.group2.swing.GradientBackGround gradientBackGround1;
    private com.group2.swing.ImageView imageView1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel maGT;
    private javax.swing.JLabel ngay;
    private javax.swing.JLabel tenLoai;
    // End of variables declaration//GEN-END:variables
}
