/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.swing;

import com.group2.entity.SanPhamMua;
import com.group2.utils.GImage;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author HieuHoang
 */
public class ItemCartPanelQR extends javax.swing.JPanel implements ListCellRenderer<SanPhamMua> {

    /**
     * Creates new form ItemCartPanelQR
     */
    public ItemCartPanelQR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgHinh = new com.group2.swing.ImageView();
        lblTenSP = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imgHinh.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icons/mas.PNG"))); // NOI18N

        lblTenSP.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblTenSP.setText("ON SERIOUS MASS 6 LBS");

        lblMaSP.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblMaSP.setForeground(new java.awt.Color(150, 150, 150));
        lblMaSP.setText("Mã sản phẩm");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Số lượng mua:");

        lblSL.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblSL.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imgHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSL)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSL)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblMaSP))
                    .addComponent(imgHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.ImageView imgHinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblSL;
    private javax.swing.JLabel lblTenSP;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends SanPhamMua> list, SanPhamMua value, int index, boolean isSelected, boolean cellHasFocus) {
        lblTenSP.setText(value.getTenSP());
        if (value.getHinh() != null) {
            imgHinh.setImage(GImage.read("sanphamIMG/", value.getHinh()));
            lblMaSP.setText(value.getMaSP());
            lblSL.setText(value.getSoLuong() + "");
        } else {
            imgHinh.setImage(GImage.read("khachhangIMG/", "macdinh.png"));
            lblMaSP.setText(value.getMaSP());
            lblSL.setText(value.getSoLuong() + "");
        }

        return this;
    }
}
