/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.swing;

import com.group2.dao.SanPhamDAO;
import com.group2.entity.GioHangSP;
import com.group2.entity.SanPhamMua;
import com.group2.utils.GImage;
import com.group2.utils.MsgBox;
import java.awt.Component;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;

/**
 *
 * @author HieuHoang
 */
public class ItemCartPanel extends javax.swing.JPanel {

    DecimalFormat df = new DecimalFormat("###,###.###");
    JPanel panelSPMua;
    SanPhamMua spm;
    JLabel labelTongTien, tongTienTT;
    GioHangSPPanel gioHangPanel;
    SanPhamDAO spDAO = new SanPhamDAO();

    /**
     * Creates new form ItemCartPanel
     */
    public ItemCartPanel() {
        initComponents();

    }

    public ItemCartPanel(SanPhamMua spm, JPanel panel, JLabel labelTongTien, GioHangSPPanel gioHangPanel, JLabel tongTienTT) {
        initComponents();
        this.panelSPMua = panel;
        this.spm = spm;
        this.labelTongTien = labelTongTien;
        this.gioHangPanel = gioHangPanel;
        this.tongTienTT = tongTienTT;
        if (spm.getHinh() != null) {
            imgHinh.setImage(GImage.read("sanphamIMG/", spm.getHinh()));
        } else {
            imgHinh.setImage(GImage.read("khachhangIMG/", "macdinh.png"));
        }

        lblTenSP.setText(spm.getTenSP());
       
        lblDonGia.setText(df.format(spm.getDonGia()) + "₫");
        lblThanhTien.setText(df.format(spm.getThanhTien()) + "₫");
        spSoLuong.setValue(spm.getSoLuong());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenSP = new javax.swing.JTextArea();
        imgHinh = new com.group2.swing.ImageView();
        btnXoa = new com.group2.swing.ButtonIcon();
        spSoLuong = new javax.swing.JSpinner();
        lblDonGia = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTenSP.setEditable(false);
        lblTenSP.setColumns(20);
        lblTenSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenSP.setLineWrap(true);
        lblTenSP.setRows(5);
        lblTenSP.setText("Sinh to bosdsad\n");
        lblTenSP.setWrapStyleWord(true);
        lblTenSP.setBorder(null);

        imgHinh.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icons/mas.PNG"))); // NOI18N

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icons/delete.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        spSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spSoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spSoLuongStateChanged(evt);
            }
        });

        lblDonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDonGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonGia.setText("960.000₫");

        lblThanhTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThanhTien.setForeground(new java.awt.Color(244, 67, 54));
        lblThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanhTien.setText("1.960.000₫");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(imgHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(imgHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        GioHangSP.listSP.remove(spm);
        panelSPMua.remove(this);
        panelSPMua.repaint();
        gioHangPanel.setSLSanPham();

        labelTongTien.setText(df.format(GioHangSP.tongTienGH()) + "₫");
        tongTienTT.setText(df.format(GioHangSP.tienThanhToan()) + "₫");
//        fillSPMuaToPanel();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void spSoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spSoLuongStateChanged
        // TODO add your handling code here:
        int SoLuong = spDAO.selectById(spm.getMaSP()).getSoLuong();
        if (SoLuong >= Integer.parseInt(spSoLuong.getValue() + "")) {
            spm.setSoLuong((int) spSoLuong.getValue());
            lblThanhTien.setText(df.format(spm.getThanhTien()) + "₫");
            labelTongTien.setText(df.format(GioHangSP.tongTienGH()) + "₫");
            tongTienTT.setText(df.format(GioHangSP.tienThanhToan()) + "₫");
        }else{
            MsgBox.alert(null, "Thông báo", "Vượt quá số lượng sản phẩm trong kho!", Alert.AlertType.ERROR);
            spSoLuong.setValue(SoLuong);
        }

    }//GEN-LAST:event_spSoLuongStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.ButtonIcon btnXoa;
    private com.group2.swing.ImageView imgHinh;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JTextArea lblTenSP;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JSpinner spSoLuong;
    // End of variables declaration//GEN-END:variables

}
