/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.swing;

import com.group2.utils.GDate;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author HieuHoang
 */
public class PanelCTGoiTap extends javax.swing.JPanel {

    /**
     * Creates new form PanelCTGoiTap
     */
    public PanelCTGoiTap(CTGoiTapModel model) {
        initComponents();
        txtMaGoiTap.setText(model.getMaGT());
        txtLoaiGoiTap.setText(model.getLoaiGT());
        txtNgayDangKi.setText(GDate.toString(model.getNgayDK(), "dd/MM/yyyy"));
        txtNgayHetHan.setText(GDate.toString(model.getNgayHH(), "dd/MM/yyyy"));

        DateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date currentDate = new Date();
        Date date1 = null;
        Date date2 = null;
        try {
            String startDate = simpleDateFormat.format(model.getNgayHH());
            String endDate = simpleDateFormat.format(currentDate);
            date1 = simpleDateFormat.parse(startDate);
            date2 = simpleDateFormat.parse(endDate);
            long getDiff = date1.getTime() - date2.getTime();
            long getDaysDiff = getDiff / (24 * 60 * 60 * 1000);
            lblNgayConLai.setText("Còn " + getDaysDiff + " ngày nữa là hết hạn!");
            if (getDaysDiff <= 0) {
                lblNgayConLai.setText("Gói tập đã hết hạn!");
            } else {
                lblNgayConLai.setText("Còn " + getDaysDiff + " ngày nữa là hết hạn!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaGoiTap = new com.group2.swing.TextField();
        txtLoaiGoiTap = new com.group2.swing.TextField();
        txtNgayDangKi = new com.group2.swing.TextField();
        txtNgayHetHan = new com.group2.swing.TextField();
        lblNgayConLai = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtMaGoiTap.setEditable(false);
        txtMaGoiTap.setBackground(new java.awt.Color(255, 255, 255));
        txtMaGoiTap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaGoiTap.setLabelText("Mã gói tập");

        txtLoaiGoiTap.setEditable(false);
        txtLoaiGoiTap.setBackground(new java.awt.Color(255, 255, 255));
        txtLoaiGoiTap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLoaiGoiTap.setLabelText("Loại gói tập");
        txtLoaiGoiTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiGoiTapActionPerformed(evt);
            }
        });

        txtNgayDangKi.setEditable(false);
        txtNgayDangKi.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayDangKi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNgayDangKi.setLabelText("Ngày đăng kí");

        txtNgayHetHan.setEditable(false);
        txtNgayHetHan.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayHetHan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNgayHetHan.setLabelText("Ngày hết hạn");

        lblNgayConLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNgayConLai.setForeground(new java.awt.Color(204, 0, 51));
        lblNgayConLai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayConLai.setText("Còn 10 ngày nữa là hết hạn!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayDangKi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(txtNgayHetHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLoaiGoiTap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaGoiTap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNgayConLai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtMaGoiTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoaiGoiTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNgayConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoaiGoiTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiGoiTapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiGoiTapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNgayConLai;
    private com.group2.swing.TextField txtLoaiGoiTap;
    private com.group2.swing.TextField txtMaGoiTap;
    private com.group2.swing.TextField txtNgayDangKi;
    private com.group2.swing.TextField txtNgayHetHan;
    // End of variables declaration//GEN-END:variables
}
