/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group2.swing;

import com.group2.dao.SanPhamDAO;
import com.group2.entity.GioHangSP;
import com.group2.entity.SanPham;
import com.group2.entity.SanPhamMua;
import com.group2.ui.HoaDonSanPhamJDailog;
//import com.group2.ui.HoaDonSanPhamJDailog;
import com.group2.ui.SanPhamUI;
import com.group2.utils.GImage;
import com.group2.utils.MsgBox;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HieuHoang
 */
public class ProductModel extends javax.swing.JPanel {

    DecimalFormat df = new DecimalFormat("###,###.###");
    /**
     * Creates new form ProductModel
     */
    SanPhamDAO spDAO = new SanPhamDAO();
    private SanPham sp;
    List<SanPhamMua> list = new ArrayList<>();
    GioHangSPPanel gioHangPanel;

    public ProductModel(SanPham sp, GioHangSPPanel gioHangPanel) {
        this.sp = sp;

        this.gioHangPanel = gioHangPanel;
        initComponents();
        loadModel(sp);
//        System.out.println(this.getComponents());
    }

    public void loadModel(SanPham sp) {
        if(sp.getHinh()!=null){
            imageView1.setImage(GImage.read("sanphamIMG/",sp.getHinh()));
        }else{
            imageView1.setImage(GImage.read("khachhangIMG/","macdinh.png"));

        }
        lblTen.setText(sp.getTenSP());
        lblGia.setText(df.format(sp.getDonGia()) + "₫");
        btnThem.setName(sp.getMaSP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientBackGround1 = new com.group2.swing.GradientBackGround();
        imageView1 = new com.group2.swing.ImageView();
        lblTen = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        button1 = new com.group2.swing.Button();
        btnThem = new com.group2.swing.Button();

        setOpaque(false);

        gradientBackGround1.setBorderRadius(10);

        imageView1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icons/mas.PNG"))); // NOI18N

        lblTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTen.setText("ON SERIOUS MASS 6 LBS");

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGia.setForeground(new java.awt.Color(255, 51, 0));
        lblGia.setText("960.000₫");

        button1.setBackground(new java.awt.Color(0, 102, 204));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Mua ngay");
        button1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(204, 0, 0));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm vào giỏ");
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientBackGround1Layout = new javax.swing.GroupLayout(gradientBackGround1);
        gradientBackGround1.setLayout(gradientBackGround1Layout);
        gradientBackGround1Layout.setHorizontalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradientBackGround1Layout.createSequentialGroup()
                        .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageView1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gradientBackGround1Layout.setVerticalGroup(
            gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBackGround1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageView1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradientBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBackGround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        MsgBox.alert(null, "Thông báo", "Thêm sản phẩm vào giỏ hàng thành công!", Alert.AlertType.SUCCESS);
        GioHangSP.spDaMua(new SanPhamMua(sp.getHinh(), sp.getMaSP(), sp.getTenSP(), sp.getDonGia(), 1));
        gioHangPanel.setSLSanPham();
    }//GEN-LAST:event_btnThemActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        GioHangSP.clearSP();
        GioHangSP.spDaMua(new SanPhamMua(sp.getHinh(), sp.getMaSP(), sp.getTenSP(), sp.getDonGia(), 1));
        new HoaDonSanPhamJDailog(gioHangPanel).setVisible(true);
        gioHangPanel.setSLSanPham();


    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.group2.swing.Button btnThem;
    private com.group2.swing.Button button1;
    private com.group2.swing.GradientBackGround gradientBackGround1;
    private com.group2.swing.ImageView imageView1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblTen;
    // End of variables declaration//GEN-END:variables
}
